### ISSUE TITLE
Donner plus de contexte sur Yocto

### ISSUE THREAD

**Issue by BrunoVernay** [ElPoulpi/LSM_Yocto#1]
Il faudrait dire un mot sur Buildroot qui est une alternative à Yocto. 
Parler de OpenEmbedded qui est utilisé par Yocto. Parler de "Linux Foundation" , dire depuis combien de temps le projet existe et que beaucoup de grosse companies (Intel, ARM, ...) participent

**Comment by ElPoulpi** [comment]
Je vais y jeter un œil sur Buildroot, et ajouter qq mots dessus

J'ai trouvé un gros e-book qui traite du Linux embarqué et qui regroupe toutes ces informations .... je vais pouvoir les ajouter pour renforcer ma doc
