### ISSUE TITLE
A propos de Toaster

### ISSUE THREAD

**Issue by BrunoVernay** [ElPoulpi/LSM_Yocto#2]
Il serait intéressant de savoir si il est utilisé dans l'équipe, leur opinion.

**Comment by ElPoulpi** [comment]
Je vais demander à Jean-Pierre, j'ai déjà un peu discuter avec lui de Yocto. S'il est utilisé je regarderai comment je peux y contribuer quand j'aurai de la substance pour une image avec SElinux

**Comment by ElPoulpi** [comment]
Toaster n'est pas utilisé au sein de l'équipe, ce n'est pas utile dans le cadre du développement sur Yocto.

De plus, l'environnement créé pour Toaster n'est pas le même que celui de Poky, il veux mieux rester sur celle ci pour la montée en compétence
