### ISSUE TITLE
LSM hook

### ISSUE THREAD

**Issue by BrunoVernay** [ElPoulpi/LSM_Yocto#3]
Attention en lisant le chapitre sur LSM on à l'impression que ce n'est pas un mécanisme de hook. 
Mais c'est bien un mecanisme de hook. Il n'est pas **generique** "multi-purpose" OK, mais c'est quand meme un hook.
Le schema serait bienvenue ici

**Comment by ElPoulpi** [comment]
Je vais ajouter ce point à ma doc.
